apiVersion: v1
kind: Service
metadata:
  name: service-mesh
  labels:
    group: service-mesh
spec:
  ports:
  - name: http-service-mesh
    protocol: TCP
    port: 80
  selector:
    group: service-mesh
