apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: webapp-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: webapp-destination
spec:
  host: webapp
  subsets:
  - name: v1
    labels:
      version: v4.0
  - name: v2
    labels:
      version: v4.1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: webapp-vs
spec:
  hosts:
  - webapp
  gateways:
  - mesh
  - webapp-gateway
  http:
  - match:
    - uri:
        prefix: /vspath
    rewrite:
      uri: /
    route:
    - destination:
        host: webapp
        subset: v1
      weight: 0
    - destination:
        host: webapp
        subset: v2
      weight: 100 
